file:
  - "./src/Api/apiTestData/apiCommon"
reporter: 'mochawesome'
reporter-options:
  - "reportDir = ../results/ApiReports/htmlReports"
  -      "overwrite = false"
  -      "timestamp = mmddyy:HHMMss"
  -      "html = true"
  -      "json = false"
  -      "reportFilename = iPromoteUApiReport"
require: 
  - "@babel/register"